sudo: required
dist: trusty

language: python

python:
  - "2.7_with_system_site_packages"

addons:
  apt:
    packages:
      - network-manager

env:
  - TOX_ENV=py27
  - TOX_ENV=flake8

before_install:
  - "sudo sed -i '/127.0.1.1/d' /etc/hosts"  # Workaround https://github.com/tornadoweb/tornado/issues/1573
  - "sudo apt-get update -qq"

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  # We just use 'coveralls-lcov' to convert lcov.info to JSON format.
  

